[package]
name = "fzero_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
fzero_gen = { path = "../fzero_gen/" }
litrs = "0.4"

[dev-dependencies]
rand = "0.8"
