[package]
name = "fzero-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_pcg = "0.3"
clap = { version = "4.2", features = ["derive"] }

[build-dependencies]
fzero = { path = "../../" }
serde = { version = "1", features = ["derive"]}
serde_json = "1"
